version: '3.8'
services:
  web:
    build: .
    restart: unless-stopped
    networks:
      - dokploy-network
    volumes:
      - app_data_light:/app/prisma
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - TELEGRAM_BOT_TOKEN=8410817305:AAE6vTlmSuBBWA2Wbwf9_p5wy3QzqF6INz8
      - TELEGRAM_CHAT_ID=376060133
      - EMAIL_PASS=wororvoeoxunilkg
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site-router-light.rule=Host(`taximezhgorod777.ru`) || Host(`www.taximezhgorod777.ru`)"
      - "traefik.http.services.site-router-light.loadbalancer.server.port=3000"
      - "traefik.docker.network=dokploy-network"

  bot:
    build: .
    command: sh -c "chmod +x wait-for-db.sh && ./wait-for-db.sh"
    restart: unless-stopped
    networks:
      - dokploy-network
    volumes:
      - app_data_light:/app/prisma
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - TELEGRAM_BOT_TOKEN=8410817305:AAE6vTlmSuBBWA2Wbwf9_p5wy3QzqF6INz8
      - TELEGRAM_CHAT_ID=376060133

networks:
  dokploy-network:
    external: true

volumes:
  app_data_light:
