version: '3.8'
services:
  web:
    image: ghcr.io/xyling12/grand-transfer-light:main
    pull_policy: always
    restart: unless-stopped
    networks:
      - dokploy-network
    volumes:
      - app_data_light:/app/prisma
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site-router-light.rule=Host(`taximezhgorod777.ru`) || Host(`www.taximezhgorod777.ru`)"
      - "traefik.http.services.site-router-light.loadbalancer.server.port=3000"
      - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true

volumes:
  app_data_light:
    external: true
    name: grandtransfer-dark-ygfq1b_app_data
